### PR TITLE
Added fix for issue#3

### PR DESCRIPTION
**Pull request by Rishabh11200**
Review it and try creating [this](https://github.com/immutable-krupal/StatusSaver/issues/3#issue-1717534399) issue.

### CODE REVIEW

**Review by krupal4 — CHANGES_REQUESTED** [review]
Instead of showing a Loading screen, we can continuously show a native splash screen while we get a color palette.

[Reference](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional)

**Comment by Rishabh11200** [comment]
> Instead of showing a Loading screen, we can continuously show a native splash screen while we get a color palette.
> 
> [Reference](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional)

Yes I'll try to implement this

**Review by krupal4 — CHANGES_REQUESTED** [review]
```dart
void main() {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  runApp(const MyApp());
}
```

while the color palette is not ready instead of Loading screen return Placeholder(), Container(), or anything else without effort, because the end user will see a splash screen while the color palette is being loaded, after completion of the future we will remove the splash screen using 
```dart
FlutterNativeSplash.remove()
```

[flutter_native_splash initialization](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional)

**Comment by immutable-krupal** [comment]
issue #3 fixed

**Comment by krupal4** [comment]
issue#3 is fixed.

**Pull request closed without merging**
